version: '3.9'
services:
  bot:
    image: vladmarlo/kogda_deploy
    restart: always
    depends_on:
      db:
        condition: service_healthy
    volumes:
       - ./docker_config.toml:/bin/config.toml
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - kogda-deploy-bot-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=deploy
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1s
      timeout: 1s
      retries: 50
volumes:
  kogda-deploy-bot-db-data:
