version: '3.9'
services:
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - kogda-deploy-bot-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=deploy
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1s
      timeout: 1s
      retries: 50
volumes:
  kogda-deploy-bot-db-data:
